name: Compile C++
on:
  push:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        sudo apt update
        sudo apt install -y g++
    - run: g++ main.cpp
    - run: ls
    - run: ./a.out
